// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>eliminar_cliente</b><br>
 * Generated     : <b>2018/07/18 17:08:48</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 amd64 6.1 <br>
 * 
 * @since  julio 18, 2018
 * @author DELL
 */
public abstract class eliminar_clienteHelper extends RationalTestScript
{
	/**
	 * Administration: with default state.
	 *		.captionText : Administration
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : Administration
	 * 		.processName : javaw.exe
	 * 		name : logFrame3
	 */
	protected TopLevelTestObject administration() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("administration"));
	}
	/**
	 * Administration: with specific test context and state.
	 *		.captionText : Administration
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : Administration
	 * 		.processName : javaw.exe
	 * 		name : logFrame3
	 */
	protected TopLevelTestObject administration(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("administration"), anchor, flags);
	}
	
	/**
	 * Close: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close() 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"));
	}
	/**
	 * Close: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"), anchor, flags);
	}
	
	/**
	 * custTable: with default state.
	 *		.class : javax.swing.JTable
	 * 		name : custTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject custTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("custTable"));
	}
	/**
	 * custTable: with specific test context and state.
	 *		.class : javax.swing.JTable
	 * 		name : custTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject custTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("custTable"), anchor, flags);
	}
	
	/**
	 * DeleteSelectedCustomer: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Customer
	 * 		name : deleteCustomer
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedCustomer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedCustomer"));
	}
	/**
	 * DeleteSelectedCustomer: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Customer
	 * 		name : deleteCustomer
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedCustomer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedCustomer"), anchor, flags);
	}
	
	/**
	 * jmb: with default state.
	 *		.class : javax.swing.JMenuBar
	 * 		name : jmb
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jmb() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jmb"));
	}
	/**
	 * jmb: with specific test context and state.
	 *		.class : javax.swing.JMenuBar
	 * 		name : jmb
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jmb(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jmb"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	

	protected eliminar_clienteHelper()
	{
		setScriptName("eliminar_cliente");
	}
	
}

